import { TExercise } from '../model/types';

export const EXERCISES: Record<string, TExercise> = {
	'1': {
		name: 'Жим гантелей в нахилі',
		slug: 'dumbell_press',
		id: '1',
		imageUrl: 'https://app-media.fitbod.me/v2/111/images/landscape/0_960x540.jpg',
		videoUrl: 'https://app-media.fitbod.me/v2/111/videos/full_1080p.mp4',
	},
	'2': {
		name: 'Тяга верхнього блоку',
		slug: 'lat_pull_down',
		imageUrl: 'https://app-media.fitbod.me/v2/429/images/landscape/0_960x540.jpg',
		id: '2',
		videoUrl: 'https://app-media.fitbod.me/v2/429/videos/full_1080p.mp4',
	},
	'3': {
		name: 'Відтискання на брусах',
		slug: 'push_up_on_bars',
		imageUrl: 'https://app-media.fitbod.me/v2/2044/images/landscape/0_960x540.jpg',
		id: '3',
		videoUrl: 'https://app-media.fitbod.me/v2/2044/videos/full_1080p.mp4',
	},
	'4': {
		name: 'Тяга гантелі до поясу',
		slug: 'dumbell_row',
		imageUrl: 'https://app-media.fitbod.me/v2/119/images/landscape/0_960x540.jpg',
		id: '4',
		videoUrl: 'https://app-media.fitbod.me/v2/119/videos/full_1080p.mp4',
	},
	'5': {
		name: 'Пулловер в блоці',
		slug: 'pull_over',
		imageUrl: 'https://app-media.fitbod.me/v2/378/images/landscape/0_960x540.jpg',
		id: '5',
		videoUrl: 'https://app-media.fitbod.me/v2/378/videos/full_1080p.mp4',
	},
	'6': {
		name: 'Жим сидячи в тренажері Сміта',
		slug: 'smith_barbell_press',
		imageUrl: 'https://app-media.fitbod.me/v2/223/images/landscape/0_960x540.jpg',
		id: '6',
		videoUrl: 'https://app-media.fitbod.me/v2/223/videos/full_1080p.mp4',
	},
	'7': {
		name: 'Махи гантелей в сторони',
		slug: 'dumbell_fly',
		imageUrl: 'https://app-media.fitbod.me/v2/121/images/landscape/0_960x540.jpg',
		id: '7',
		videoUrl: 'https://app-media.fitbod.me/v2/121/videos/full_1080p.mp4',
	},
	'8': {
		name: 'Підйоми ніг + скручування',
		slug: 'leg_lifts',
		imageUrl: 'https://app-media.fitbod.me/v2/233/images/landscape/0_960x540.jpg',
		id: '8',
		videoUrl: 'https://app-media.fitbod.me/v2/233/videos/full_1080p.mp4',
	},

	'9': {
		name: 'Розгинання ніг',
		slug: 'leg_extension',
		imageUrl: 'https://app-media.fitbod.me/v2/217/images/landscape/0_960x540.jpg',
		id: '9',
		videoUrl: 'https://app-media.fitbod.me/v2/217/videos/full_1080p.mp4',
	},
	'10': {
		name: 'Жим ногами',
		slug: 'leg_press',
		imageUrl: 'https://app-media.fitbod.me/v2/218/images/landscape/0_960x540.jpg',
		id: '10',
		videoUrl: 'https://app-media.fitbod.me/v2/218/videos/full_1080p.mp4',
	},
	'11': {
		name: 'Присідання в СМІТІ',
		slug: 'smith_squat',
		imageUrl: 'https://app-media.fitbod.me/v2/354/images/landscape/0_960x540.jpg',
		id: '11',
		videoUrl: 'https://app-media.fitbod.me/v2/354/videos/full_1080p.mp4',
	},
	'12': {
		name: 'Підйоми на носки в гак',
		slug: 'rack_squat',
		imageUrl: 'https://app-media.fitbod.me/v2/302/images/landscape/0_960x540.jpg',
		id: '12',
		videoUrl: 'https://app-media.fitbod.me/v2/302/videos/full_1080p.mp4',
	},
	'13': {
		name: 'Підйом гантелей з супінацією',
		slug: 'bicep_curl',
		imageUrl: 'https://app-media.fitbod.me/v2/102/images/landscape/0_960x540.jpg',
		id: '13',
		videoUrl: 'https://app-media.fitbod.me/v2/102/videos/full_1080p.mp4',
	},
	'14': {
		name: 'Розгинання на тріцепс (канат | пряма рукоятка)',
		slug: 'triceps_extension',
		imageUrl: 'https://app-media.fitbod.me/v2/295/images/landscape/0_960x540.jpg',
		id: '14',
		videoUrl: 'https://app-media.fitbod.me/v2/295/videos/full_1080p.mp4',
	},
	'15': {
		name: 'Підтягування широким хватом',
		slug: 'pull_up',
		imageUrl: 'https://app-media.fitbod.me/v2/279/images/landscape/0_960x540.jpg',
		id: '15',
		videoUrl: 'https://app-media.fitbod.me/v2/279/videos/full_1080p.mp4',
	},
	'16': {
		name: 'Жим в тренажері Сміта в нахилі',
		slug: 'smith_bench_press',
		imageUrl: 'https://app-media.fitbod.me/v2/347/images/landscape/0_960x540.jpg',
		id: '16',
		videoUrl: 'https://app-media.fitbod.me/v2/347/videos/full_1080p.mp4',
	},
	'17': {
		name: 'Горизонтальна тяга сидячи в блоці',
		slug: 'pull_row',
		imageUrl: 'https://app-media.fitbod.me/v2/69/images/landscape/0_960x540.jpg',
		id: '17',
		videoUrl: 'https://app-media.fitbod.me/v2/69/videos/full_1080p.mp4',
	},
	'18': {
		name: 'Бабочка',
		slug: 'fly',
		imageUrl: 'https://app-media.fitbod.me/v2/239/images/landscape/0_960x540.jpg',
		id: '18',
		videoUrl: 'https://app-media.fitbod.me/v2/239/videos/full_1080p.mp4',
	},
	'19': {
		name: 'Ричажна горизонтальна тяга',
		slug: 'lever_pull_row',
		imageUrl: 'https://app-media.fitbod.me/v2/244/images/landscape/0_960x540.jpg',
		id: '19',
		videoUrl: 'https://app-media.fitbod.me/v2/244/videos/full_1080p.mp4',
	},
	'20': {
		name: 'Махи гантелей сидячи (задня дельта)',
		slug: 'dumbell_fly_back',
		imageUrl: 'https://app-media.fitbod.me/v2/25/images/landscape/0_960x540.jpg',
		id: '20',
		videoUrl: 'https://app-media.fitbod.me/v2/25/videos/full_1080p.mp4',
	},
	'21': {
		name: 'Скручування',
		slug: 'curls',
		imageUrl: 'https://app-media.fitbod.me/v2/92/images/landscape/0_960x540.jpg',
		id: '21',
		videoUrl: 'https://app-media.fitbod.me/v2/92/videos/full_1080p.mp4',
	},
	'22': {
		name: 'Згинання ніг сидячи',
		slug: 'bending_legs',
		imageUrl: 'https://app-media.fitbod.me/v2/305/images/landscape/0_960x540.jpg',
		id: '22',
		videoUrl: 'https://app-media.fitbod.me/v2/305/videos/full_1080p.mp4',
	},
	'23': {
		name: 'Румунська тяга',
		slug: 'roman_pull',
		imageUrl: 'https://app-media.fitbod.me/v2/292/images/landscape/0_960x540.jpg',
		id: '23',
		videoUrl: 'https://app-media.fitbod.me/v2/292/videos/full_1080p.mp4',
	},
	'24': {
		name: 'Молотки c гантелями',
		slug: 'hammer_curl',
		imageUrl: 'https://app-media.fitbod.me/v2/158/images/landscape/0_960x540.jpg',
		id: '24',
		videoUrl: 'https://app-media.fitbod.me/v2/158/videos/full_1080p.mp4',
	},
	'25': {
		name: 'Згинання в Скота',
		slug: 'scott_curl',
		imageUrl: 'https://app-media.fitbod.me/v2/276/images/landscape/0_960x540.jpg',
		id: '25',
		videoUrl: 'https://app-media.fitbod.me/v2/276/videos/full_1080p.mp4',
	},
	'26': {
		name: 'Франц жим гантелями',
		slug: 'french_curl',
		imageUrl: 'https://app-media.fitbod.me/v2/124/images/landscape/0_960x540.jpg',
		id: '26',
		videoUrl: 'https://app-media.fitbod.me/v2/124/videos/full_1080p.mp4',
	},
};
